services:
    MetaModels\DropzoneFileUploadBundle\Hook\InitialIzeDropzoneUpload:
        public: false
        arguments:
            - "@translator"
            - "@request_stack"
            - "@mm.dropzone_file_upload.finder"
            - "%kernel.project_dir%"
        tags:
            -   name: contao.hook
                hook: parseWidget
