services:
    MetaModels\DropzoneFileUploadBundle\Hook\InitialIzeDropzoneUpload:
        public: false
        arguments:
            - "@translator"
            - "@request_stack"
        tags:
            -   name: contao.hook
                hook: parseWidget
